# These jobs are triggered automatically and they test code, examples, and wheels.
# Additional checks can be manually triggered
variables:
  nightlyRelease: $[and(eq(variables['nightly_check'], true), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))]

trigger:
- master

pr:
- master

jobs:

- job: 'manylinux2010'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '36'
        python.version: '3.6'
      Python37:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '37'
        python.version: '3.7'
      Python38:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '38'
        python.version: '3.8'
  variables:
    CCACHE_DIR: $(Pipeline.Workspace)/ccache

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - task: Cache@2
    inputs:
      key: '"ccache-wheels-v2020.08.08" | $(Agent.OS) | "$(python.version)"'
      path: $(CCACHE_DIR)
    displayName: ccache

  - bash: |
      set -e
      sed -i "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      sed -i "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Change name to giotto-tda-nightly'

  - task: Bash@3
    inputs:
      filePath: .azure-ci/build_manylinux2010.sh
    env:
      python_ver: $(python_ver)
      CCACHE_DIR: $(CCACHE_DIR)
    displayName: 'Run docker container, install and uninstall dev environment, test with pytest and flake8, build the wheels'

  - script: |
      set -e
      python -m pip install --upgrade pip
      pip install dist/*manylinux2010*.whl
    displayName: 'Install the wheels'

  - script: |
      set -e
      pip install pytest pytest-cov pytest-azurepipelines pytest-benchmark hypothesis
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    displayName: 'Test the wheels with pytest'

  - script: |
      set -e
      pip install pandas openml matplotlib
      pip install "papermill==1.2.1"
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    condition: eq(variables['notebooks_check'], 'true')
    displayName: 'Test jupyter notebooks with papermill'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'

  - bash: |
      set -e
      pip install twine
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*manylinux2010*.whl
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Upload nightly wheels to PyPI'


- job: 'macOS1014'
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  variables:
    CCACHE_DIR: $(Pipeline.Workspace)/ccache

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      set -e
      sed -i.bak "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      rm setup.py.bak
      sed -i.bak "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
      rm gtda/_version.py.bak
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Change name to giotto-tda-nightly'

  - task: Cache@2
    inputs:
      key: '"ccache-v2020.08.08" | $(Agent.OS) | "$(python.version)"'
      path: $(CCACHE_DIR)
    displayName: ccache

  - script: |
      set -e
      brew update
      brew install boost ccache
    displayName: 'Install system dependencies'

  - script: |
      set -e
      python -m pip install --upgrade pip setuptools
      source .azure-ci/setup_ccache.sh
      python -m pip install -e ".[dev]"
      ccache -s
    displayName: 'Install dependencies and dev environment'

  - script: |
      set -e
      pytest gtda --cov --cov-report xml
    displayName: 'Test dev install with pytest, upload coverage report'

  - script: |
      set -e
      flake8
    displayName: 'Test dev install with flake8'

  - script: |
      set -e
      pip uninstall -y giotto-tda
      pip uninstall -y giotto-tda-nightly
    displayName: 'Uninstall giotto-tda/giotto-tda-nightly'

  - script: |
      set -e
      pip install wheel
      python setup.py bdist_wheel
    displayName: 'Build the wheels'

  - script: pip install dist/*.whl
    displayName: 'Install the wheels'

  - script: |
      set -e
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    displayName: 'Test the wheels with pytest'

  - script: |
      set -e
      python -m pip install -e ".[examples]"
      pip install "papermill==1.2.1"
      cd examples
      for n in *.ipynb
      do
        papermill --start_timeout 2000 $n -
      done
    displayName: 'Test jupyter notebooks with papermill'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - script: |
      set -e
      pip install twine
      twine check dist/*
    displayName: 'Check distribution with twine'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'

  - bash: |
      set -e
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Upload nightly wheels to PyPI'


- job: 'win2016'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python_ver: '36'
        python.version: '3.6'
      Python37:
        python_ver: '37'
        python.version: '3.7'
      Python38:
        python_ver: '38'
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      set -e
      sed -i "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
      sed -i "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Change name to giotto-tda-nightly'

  # Set BOOST_ROOT_PIPELINE to the version used in the pipeline
  # See https://github.com/actions/virtual-environments/issues/687#issuecomment-616345933
  - script: |
      echo "##vso[task.setvariable variable=BOOST_ROOT_PIPELINE]%BOOST_ROOT_1_72_0%"
    displayName: 'Set env variable for boost version'

  - script: |
      python -m pip install --upgrade pip setuptools
      python -m pip install -e ".[dev]"
    displayName: 'Install dev environment'

  - script: |
      pytest gtda --no-cov --no-coverage-upload || exit /b
    displayName: 'Test dev install with pytest'

  - script: |
      pip uninstall -y giotto-tda
      pip uninstall -y giotto-tda-nightly
    displayName: 'Uninstall giotto-tda/giotto-tda-nightly dev'

  - bash: |
      set -e
      sed -i $'s/\r$//' README.rst
      pip install wheel
      python setup.py bdist_wheel
    displayName: 'Build the wheels'

  - bash: pip install dist/*.whl
    displayName: 'Install the wheels'

  - script: |
      mkdir tmp_test_cov
      cd tmp_test_cov
      pytest --pyargs gtda --ignore-glob='*externals*' --no-cov --no-coverage-upload
    displayName: 'Test the wheels with pytest'

  - script: |
      python -m pip install -e ".[examples]"
      pip install "papermill==1.2.1"
      cd examples
      FOR %%n in (*.ipynb) DO (papermill --start_timeout 2000 %%n - || exit /b)
    condition: eq(variables['notebooks_check'], 'true')
    displayName: 'Test jupyter notebooks with papermill'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'

  - bash: |
      set -e
      pip install twine
      twine upload -u giotto-learn -p $(pypi_psw) --skip-existing dist/*
    condition: eq(variables.nightlyRelease, true)
    displayName: 'Upload nightly wheels to PyPI'

- job: 'Documentation'
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
  variables:
    EXECUTE: 'true'
    RUNNOTEBOOKS: TRUE
    VERSION: azure-test
    GITDIR: /tmp/gtda-docs

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: |
        set -e
        brew update
        brew install boost
      displayName: 'Install system dependencies'

    - script: |
        set -e
        python -m pip install --upgrade pip setuptools
        python -m pip install -e ".[dev,doc]"
      displayName: 'Install dependencies and dev environment'

    - script: |
        set -e
        python -m pip uninstall -y sphinx-rtd-theme
        python -m pip install git+https://github.com/wreise/sphinx_rtd_theme.git@aeafa25faef29b615aa496ed01a427b86412d26e
      displayName: 'Install the custom sphinx_rtd_theme'

    - script: |
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      displayName: 'Create .ssh/known_hosts'
      condition: ne(variables['Build.Reason'], 'PullRequest')

    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: ~/.ssh/known_hosts
        sshPublicKey: $(KEY_GTDA-DOCS_PUB)
        sshKeySecureFile: KEY_GTDA-DOCS
      condition: ne(variables['Build.Reason'], 'PullRequest')

    - script: |
        set -e
        cd /tmp/
        git clone git@github.com:giotto-learn/gtda-docs.git
        cd gtda-docs
        git config user.email "maintainers@giotto.ai"
        git config user.name "giotto-maintainers"
        git checkout -b deploytests
        # TODO: copy docs to the right folder and git add them
        # git commit -m "Test empty commit (azure pipelines)" --allow-empty
        # git push -u origin master
        # cd -
      displayName:  'Clone the docs and configure the username'
      condition: ne(variables['Build.Reason'], 'PullRequest')

    - script: |
        set -e
        cd doc/
        make all-gh
        make gh-commit
      displayName: 'Build and commit the docs'
      condition: ne(variables['Build.Reason'], 'PullRequest')

    - script: |
        cd /tmp/gtda-docs
        git push -u origin deploytests
      displayName: 'Push the docs to master'
      condition:
